-- Deploy madjikarite:data to pg

BEGIN;

INSERT INTO "category" ("name")
VALUES
('savons solides'), -- id 1
('savons liquides'), -- id 2
('beurres corporels'), -- id 3
('beurres à lèvres'), -- id 4
('beurres de karité pur non raffinés'), -- id 5
('coffrets'), -- id 6
('cartes cadeaux'); -- id 7

INSERT INTO "product" ("name", "short_description", "full_description", "ingredients", "packaging", "weight", "price", "stock", "category_id")
VALUES
('Lavande 145-155g', 'Savon naturel/Artisanal/ hydratant fait main au beurre de karité bio: sur-gras, non desséchant, crémeux avec une mousse riche. Fabriqué à partir d''ingrédients naturels/biologiques  et des vrais bourgeons de lavande.
Hydratant. Adoucissant. Pour tous types de peau. Saponification à froid. Fabriqué à la
', 'Composition Les ingrédients clés comprennent : le beurre de karité bio, l''huile de coco, l''huile d''olive, l''huile de tournesol, l''huile essentielle de lavande et les fleurs de lavande.
Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. Le beurre protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
L''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive L''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. l''huile essentielle de lavande Régénérante et réparatrice, cette huile essentielle de Lavande s''utilise sur les cicatrices, petites plaies et infections cutanées. Calmante et sédative, elle favorise le sommeil, l''élimination des tensions nerveuses, des migraines et des douleurs musculaires.', 'Ingrédients issus de l''agriculture biologique. INCI : sodium oliveate (huile d''olive saponifiée), sodium cocate (huile de noix de coco saponifiée), Aqua (eau), Butyrospermum parkii butter ( beurre de karité), sunflower seed oil, Lavandula angustifolia oil, Lavandula vera, Tocopheryl acetate. Allergene : geraniol, linalool, limonene.','145-155g', 155, 6, 9, 1),

('Citron&mangue/Herbes de Provence 145-155g', 'savon naturel/artisanal/hydratant, sur-gras au beurre de karité bio. Un savon crémeux avec une mousse riche pour tous  types de peau. Fabriqué à partir d''ingrédients naturels de mangue&citron.
Hydratant. Adoucissant. Pour tous types de peau. Saponification à froid. Fabriqué à la
', 'Les ingrédients clés comprennent : le beurre de karité bio, huile de coco, l''huile d''olive, l''huile de tournesol, parfum de mangue et citron.
Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance.
Parfum de mangue et citron. Le parfum de mangue reconnu pour ces propriétés assouplissantes, adoucissantes, nourrissantes, cicatrisantes et filtre solaire naturel léger, ajouté  au citron qui adoucit et tonifie l''épiderme en contractant les tissus, c''est deux parfum sont parfait  pour votre peau.', 'Ingrédients issus de l''agriculture biologique. INCI: sodium oliveate (huile d''olive saponifiée), sodium cocate (huile de noix de coco saponifiée), Aqua (eau), Butyrospermum parkii butter (beurre de karité), sunflower seed oil, Citrus limon peel oil, Mangifera Indica, Tocopheryl acetate. Allergene: citral, geraniol, linalool,limonene,benzyl benzoate, benzyl salicylate,citronellol, hexyl cinnanic, liliestralis22, metyl ionone, orange terpenes/d-limonene.','145-155g', 155, 6, 2, 1),

('Géranium & Rose 145-155g', 'savon naturel/artisanal/ hydratant, sur-gras, non desséchant, au beurre de karité bio. Un savon crémeux avec une mousse riche pour tous types de peau. Fabriqué à partir d''ingrédients naturels de rose et géranium.
Hydratant. Adoucissant. Pour tous types de peau. Saponification
', 'Les ingrédients clés comprennent : le beurre de karité bio, huile de coco, l''huile d''olive, l''huile de tournesol, parfum de rose et géranium.
Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. Parfum de Géranium et Rose.
Géranium est très efficace Pour assécher une peau trop grasse, hydrater une peau sèche et refermer les pores dilatés de la peau. La rose est connue pour ses actions régénérant cutanée puissante et anti-âge. Elle est idéale pour nourrir les peaux sèches, abîmées et couperosées, lutter contre les rides et atténuer les vergetures et cicatrices. Ingrédients issus de l''agriculture biologique.', 'INCI : Ingredients : sodium oliveate (huile d''olive saponifiée), sodium cocate (huile de noix de coco saponifiée), Aqua (eau), Butyrospermum parkii butter (beurre de karité), sunflower seed oil, Pelargonium asperum oil, Aniba rosaeodora wood , Tocopheryl acetate, allergene : citral, geraniol linalool, citronellol, limonene, benzyl benzoate.','145-155g', 155, 6, 1, 1),

('ARGILE VERTE/ORANGE&ABRICOT 145-155G', 'L''idéal pour le visage. Gomme les peaux mortes. l''argile est une matière vivante : elle enrichie, rééquilibre, protège, régénère chaque cellule du corps.  l''orange et l''abricot redonnent  de éclat à votre visage.utiliser 2fois/semaine. Fabriqué à partir des ingrédients naturels/biologiques.', 'Les ingrédients clés comprennent : le beurre de karité bio, huile de coco, l''huile d''olive, l''huile de tournesol, parfum de d''orange et d''abricot.
Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance.', 'INCI : sodium oliveate (huile d''olive saponifiée), sodium cocate (huile de noix de coco saponifiée), Aqua (eau), Butyrospermum parkii butter (beurre de karité), sunflower seed oil, Citrus aurantium dulcis oil/ linalol, Tocopheryl acetate. Allergene','145-155g', 155, 6, 15, 1),

('ARGILE BLANCHE/MANDRINE &CITRON 145-155G', ' Eliminer les taches noirs/marrons et les boutons. l''argile blanche, citron et mandarine, apportent une douceur infinie à votre peau .Utiliser deux fois par semaine sur le visage, elle révèle instantanément l''éclat de votre peau.tout types de peaux/Fabriqué à partir ', ' Les ingrédients clés comprennent : le beurre de karité bio, l''huile de coco, l''huile d''olive, l''huile de tournesol.
Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. Ingrédients issus de l''agriculture biologique.', 'Ingredients : sodium oliveate (huile d''olive saponifiée), sodium cocate (huile de noix de coco saponifiée), Aqua (eau), Butyrospermum parkii butter (beurre de karité),sunflower seed , Citrus limon peel oil/Citrus reticulata oil, Tocopheryl acetate. Allergene : citral,geraniol, linalool,limonene.', '145-155g', 155, 6, 10, 1),

('Moringa 145-155g', 'Savon merveilleux,l''huile de Moringa à des vertus anti-âge reconnues:elle hydrate votre peau,réduit les rides. sans parfum ajouté  pour ne garder que les propriétés de huile de moringa,un savon qui rajeunit. Fabriqué à partir des ingrédients naturels/biologiques.
Hydratant. Adoucissant. Pour tous
', 'Les ingrédients clés comprennent : l''huile de moringa, le beurre de karité bio, l''huile de coco, l''huile d''olive, l''huile de tournesol. l''huile de moringa Pour les peaux fatiguées, ridées, vieillissantes. Cette  huile possède des vertus anti-âge reconnues, qui renforcent les tissus de la peau et minimisent la formation des rides. La vitamine C est efficace pour la régénération des cellules.
Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. Ingrédients issus de l''agriculture biologique.', 'Ingredients : sodium oliveate (huile d''olive saponifiée), sodium cocate (huile de noix de coco saponifiée), Aqua (eau), Butyrospermum parkii butter (beurre de karité), Moringa Oleifera Seed Oil , Tocopheryl acetate. Pas d''allergene Code : MKM01 ','145-155g', 155, 6, 8, 1),

('Citronnelle&Menthe 145-155g', 'l''huile de “neem”/”Margousier”  .Ce savon est fait pour calmer vos démangeaisons, adoucir vos  cicatrices et apaiser vos rougeurs. Fabriqué à partir des ingrédients naturels/biologiques.
Hydratant. Adoucissant. Pour tous types de peau. Saponification à froid. Fabriqué à la main à partir', 'Les ingrédients clés comprennent : l''huile de neem bio, le beurre de karité bio, l''huile de coco, l''huile d''olive, l''huile de tournesol. l''huile de neem Le Neem, aussi appelé « margousier » ou « lilas de perse », l''huile de neem est Le traitement des peaux à problèmes : la lutte contre les poux et les puces, la protection des végétaux et le soin des plantes, la protection contre les moustiques et de nombreux insectes.
Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance
Parfum de mente et citronnelle l''huile de mente verte  ajouté  à la citronnelle calme et apaise la peau. Ingrédients issus de l''agriculture biologique.', 'Ingredients : sodium oliveate (huile d''olive saponifiée), sodium cocate (huile de noix de coco saponifiée), Aqua (eau), Butyrospermum parkii butter ( beurre de karité), Moringa Oleifera Seed Oil , Mentha piperita oil /Citrus limon peel oil, Tocopheryl acetate.allergene : citral, eugenol,geraniol,farnesol,linalool,citronellol,limoene, amyl cinamal aldehyde, coumarin,iso eugenol, liliestralis22,methyl lonone, orange terpenes/d-limonene.','145-155g', 155, 6, 4, 1),

('Muguet&Néroli 145-155g', 'Savon naturel/artisanal/ hydratant, sur-gras, au beurre de karité bio. Un savon crémeux avec une mousse riche pour tous types de peau. Fabriqué à partir d''ingrédients naturels de muguet& néroli.
Hydratant. Adoucissant. Pour tous types de peau. Saponification à froid. Fabriqué
', 'Les ingrédients clés comprennent : le beurre de karité bio, huile de coco, l''huile d''olive, l''huile de tournesol, parfum de néroli et muguet.
Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. Ingrédients issus de l''agriculture biologique.', 'Ingredients : sodium oliveate (huile d''olive saponifiée), sodium cocate (huile de noix de coco saponifiée), Aqua (eau), Butyrospermum parkii butter (beurre de karité), sunflower seed oil, Citrus aurantium amara flower oil / convallaria majalis , Tocopheryl acetate. Allergene : citral, hydroxylcitronellal, geraniol,linalool, citronellol,limonene. Code : MKMN01','145-155g', 155, 6, 12, 1),

('Carotte&Fruit de la passion 145-155g', 'Riche en béta carotène « vitamine bonne mine par excellence », cette huile illumine votre teint, lui redonne vigueur et beauté.Un savon hydratant, sur-gras, non desséchant, à l''huile de carotte.Fabriqué à partir des ingrédients naturels/biologiques. Convient aux végétaliens.
Hydratant. Adoucissant.', 'Les ingrédients clés comprennent : huile de carotte, le beurre de karité bio, huile de coco, l''huile d''olive, l''huile de tournesol. Huile de carotte c''est une huile orangée, car très riche en béta-carotène, la fameuse vitamine bonne mine. On l''utilise pour se préparer au soleil autant que pour prolonger son bronzage ou donner plus de lumière à son teint. c''est un peu l''auto-bronzant de la Slow Cosmétique. Très peu grasse, cette huile pénètre bien et n''a pas vraiment d''odeur.
Beurre de karité Le beurre de karité pur est un émollient naturel qui se soucie, guérit et protège la peau. Le beurre protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon).
Hydrate et nourrit la peau en profondeur.
Huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules.
Huile de d''olive l''huile d''olive est un excellent hydratant et convient à tous les types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse la peau hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E, l''huile d''olive est un puissant antioxydant.
Huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance.
Ingrédients issus de l''agriculture biologique.', 'Ingrédients : sodium oliveate (huile d''olive saponifiée), sodium cocate (huile de noix de coco saponifiée), Aqua (eau), Butyrospermum parkii butter( beurre de karité), Daucus carota sativa seed oil, Passiflora edulis var, Tocopheryl acetate, Allergene : benzyl benzoate, eugenol, geranol, Hexyl cinnamic aldehyde.','145-155g', 155, 6, 5, 1),

('mangue&citron/Herbes de Provence 100g', 'savon naturel/artisanal/hydratant, sur-gras au beurre de karité bio. Un savon crémeux avec une mousse riche pour tous  types de peau. Fabriqué à partir d''ingrédients naturels de mangue&citron.
Hydratant. Adoucissant. Pour tous types de peau. Saponification à froid.', 'Les ingrédients clés comprennent : le beurre de karité bio, huile de coco, l''huile d''olive, l''huile de tournesol, parfum de mangue et citron.
Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance.
Parfum de mangue et citron. Le parfum de mangue reconnu pour ces propriétés assouplissantes, adoucissantes, nourrissantes, cicatrisantes et filtre solaire naturel léger, ajouté  au citron qui adoucit et tonifie l''épiderme en contractant les tissus, c''est deux parfum sont parfait  pour votre peau.', 'Ingrédients issus de l''agriculture biologique. INCI: sodium oliveate (huile d''olive saponifiée), sodium cocate (huile de noix de coco saponifiée), Aqua (eau), Butyrospermum parkii butter (beurre de karité), sunflower seed oil, Citrus limon peel oil, Mangifera Indica, Tocopheryl acetate. Allergene: citral, geraniol, linalool,limonene,benzyl benzoate, benzyl salicylate,citronellol, hexyl cinnanic, liliestralis22, metyl ionone, orange terpenes/d-limonene.','100g', 100, 4, 0, 1),

('Lavande/100g', 'Savon naturel/Artisanal/ hydratant fait main au beurre de karité bio: sur-gras, non desséchant,crémeux avec une mousse riche.Fabriqué à partir d''ingrédients naturels/biologiques  et des vrais bourgeons de lavande.
Hydratant. Adoucissant. Pour tous types de peau. Saponification à froid.', 'Composition Les ingrédients clés comprennent : le beurre de karité bio, l''huile de coco, l''huile d''olive, l''huile de tournesol, l''huile essentielle de lavande et les fleurs de lavande.
Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. Le beurre protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. l''huile essentielle de lavande Régénérante et réparatrice, cette huile essentielle de Lavande s''utilise sur les cicatrices, petites plaies et infections cutanées. Calmante et sédative, elle favorise le sommeil, l''élimination des tensions nerveuses, des migraines et des douleurs musculaires.', 'Ingrédients issus de l''agriculture biologique. INCI : sodium oliveate (huile d''olive saponifiée), sodium cocate (huile de noix de coco saponifiée), Aqua (eau), Butyrospermum parkii butter ( beurre de karité), sunflower seed oil, Lavandula angustifolia oil, Lavandula vera, Tocopheryl acetate. Allergene : geraniol, linalool, limonene.','100g', 100, 4, 0, 1),

('Savon Neutre/500ml', 'Savon naturel/artisanal/ hydratant, sur-gras, non desséchant, au beurre de karité bio. Pour tous types de peau. Fabriqué à partir d''ingrédients naturels  et sans parfum. Saponification traditionnelle à la potasse. Agiter avant utilisation& refermer après usage.
', 'Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. Il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. sans parfum
Géranium est très efficace Pour assécher une peau trop grasse, hydrater une peau sèche et refermer les pores dilatés de la peau. La rose est connue pour ses actions régénérant cutanées puissantes et anti-âges. Elle est idéale pour nourrir les peaux sèches, abîmées et couperosées, lutter contre les rides et atténuer les vergetures et cicatrices. Ingrédients issus de l''agriculture biologique.', 'Ingrédients : INCI:   potassium sunflower seed oil (huile de tournesol)),  Aqua ( eau), Potassium cocate (huile de noix de coco saponifié),  Potassium  oliveate (huile d''olive saponifié) , Butyrospermum parkii butter( beurre de karité saponifié), tocopheryl acetate( vitamine E naturelle). Sans allergène. ','500ml', 500, 11, 2, 2),

('Savon Neutre/200ml', 'Savon naturel/artisanal/ hydratant, sur-gras, non desséchant, au beurre de karité bio. Pour tous types de peau. Fabriqué à partir d''ingrédients naturels  et sans parfum. Saponification traditionnelle à la potasse. Agiter avant utilisation& refermer après usage. ', 'Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. Il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. sans parfum
Géranium est très efficace Pour assécher une peau trop grasse, hydrater une peau sèche et refermer les pores dilatés de la peau. La rose est connue pour ses actions régénérant cutanées puissantes et anti-âges. Elle est idéale pour nourrir les peaux sèches, abîmées et couperosées, lutter contre les rides et atténuer les vergetures et cicatrices. Ingrédients issus de l''agriculture biologique.', 'Ingrédients : INCI:   potassium sunflower seed oil (huile de tournesol)),  Aqua ( eau), Potassium cocate (huile de noix de coco saponifié),  Potassium  oliveate (huile d''olive saponifié) , Butyrospermum parkii butter( beurre de karité saponifié), tocopheryl acetate( vitamine E naturelle). Sans allergène.','200ml', 200, 5.80, 1, 2),

('Fruit de la passion/500ml', 'Savon naturel/artisanal/ hydratant, sur-gras, non desséchant, au beurre de karité bio. Pour tous types de peau. Fabriqué à partir d''ingrédients naturels de rose et géranium. Saponification traditionnelle à la potasse. Agiter avant utilisation& refermer après usage.
', 'Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. Il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. Parfum fruit de la passion.
Géranium est très efficace Pour assécher une peau trop grasse, hydrater une peau sèche et refermer les pores dilatés de la peau. La rose est connue pour ses actions régénérant cutanées puissantes et anti-âges. Elle est idéale pour nourrir les peaux sèches, abîmées et couperosées, lutter contre les rides et atténuer les vergetures et cicatrices. Ingrédients issus de l''agriculture biologique.', 'Ingrédients : INCI: potassium  sunflower seed oil (huile de tournesol)),  Aqua (eau), Potassium cocate (huile de noix de coco saponifié),  Potassium  oliveate (huile d''olive saponifié), Butyrospermum parkii butter (beurre de karité saponifié), tocopheryl acetate( vitamine E naturelle),  passiflora edulis var oil (arome naturel de fruit de la passion). Allergènes : benzyl benzoate, eugenol, geranol, hexyl cinnamic aldehyde.','500ml', 500, 13, 6, 2),

('Fruit de la passion/250ml', 'Savon naturel/artisanal/ hydratant, sur-gras, non desséchant, au beurre de karité bio. Pour tous types de peau. Fabriqué à partir d''ingrédients naturels de fruit de la passion . Saponification traditionnelle à la potasse. Agiter avant utilisation& refermer après usage.
', 'Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. Il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. Parfum  fruit de la passion.
Géranium est très efficace Pour assécher une peau trop grasse, hydrater une peau sèche et refermer les pores dilatés de la peau. La rose est connue pour ses actions régénérant cutanées puissantes et anti-âges. Elle est idéale pour nourrir les peaux sèches, abîmées et couperosées, lutter contre les rides et atténuer les vergetures et cicatrices. Ingrédients issus de l''agriculture biologique.', 'Ingrédients : INCI: potassium  sunflower seed oil (huile de tournesol)),  Aqua (eau), Potassium cocate (huile de noix de coco saponifié),  Potassium  oliveate (huile d''olive saponifié), Butyrospermum parkii butter (beurre de karité saponifié), tocopheryl acetate( vitamine E naturelle),  passiflora edulis var oil (arome naturel de fruit de la passion). Allergènes : benzyl benzoate, eugenol, geranol, hexyl cinnamic aldehyde.','250ml', 250, 7.50, 3, 2),

('Rose&géranium/500ml', 'Savon naturel/artisanal/ hydratant, sur-gras, non desséchant, au beurre de karité bio. Pour tous types de peau. Fabriqué à partir d''ingrédients naturels de rose et géranium. Saponification traditionnelle à la potasse. Agiter avant utilisation& refermer après usage.
', 'Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. Il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. Parfum de Géranium et Rose.
Géranium est très efficace Pour assécher une peau trop grasse, hydrater une peau sèche et refermer les pores dilatés de la peau. La rose est connue pour ses actions régénérant cutanées puissantes et anti-âges. Elle est idéale pour nourrir les peaux sèches, abîmées et couperosées, lutter contre les rides et atténuer les vergetures et cicatrices. Ingrédients issus de l''agriculture biologique.', 'Ingrédients :  potassium sunflower seed oil (huile de tournesol)),  Aqua (eau), Potassium cocate (huile de noix de coco saponifié),  Potassium  oliveate (huile d''olive saponifié), Butyrospermum parkii butter (beurre de karité saponifié), tocopheryl acetate( vitamine E naturelle ), perlargonium asperum oil( huile essentielle de géranium), aniba rosaeodora wood( huile essentielle de rose des bois). Allergenes : citral, geraniol linalool, citronellol, limonene, benzyl benzoate. ','500ml', 500, 13, 4, 2),

('Rose&géranium/250ml', 'Savon naturel/artisanal/ hydratant, sur-gras, non desséchant, au beurre de karité bio. Pour tous types de peau. Fabriqué à partir d''ingrédients naturels de rose et géranium. Saponification traditionnelle à la potasse. Agiter avant utilisation& refermer après usage.
', 'Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. Il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. Parfum de Géranium et Rose.
Géranium est très efficace Pour assécher une peau trop grasse, hydrater une peau sèche et refermer les pores dilatés de la peau. La rose est connue pour ses actions régénérant cutanées puissantes et anti-âges. Elle est idéale pour nourrir les peaux sèches, abîmées et couperosées, lutter contre les rides et atténuer les vergetures et cicatrices. Ingrédients issus de l''agriculture biologique.', 'Ingrédients : INCI:   potassium sunflower seed oil (huile de tournesol)),  Aqua (eau), Potassium cocate (huile de noix de coco saponifié),  Potassium  oliveate (huile d''olive saponifié), Butyrospermum parkii butter (beurre de karité saponifié), tocopheryl acetate( vitamine E naturelle ), perlargonium asperum oil( huile essentielle de géranium), aniba rosaeodora wood( huile essentielle de rose des bois). Allergenes : citral, geraniol linalool, citronellol, limonene, benzyl benzoate.','250ml', 250, 7.50, 1, 2),

('Savon Pour les mains/250ml', 'Spécial  pour les mains  saines et purifiées. Savon liquide naturel/artisanal  Tea tree (arbre à Thé)  et Ravintsara./ 250ml
Formulé avec les huiles essentielles purifiantes de Tea tree (arbre à Thé)  et Ravintsara
 Formule non desséchante  pour des mains douces et hydratées', 'Spécial  pour les mains  saines et purifiées. Savon liquide naturel/artisanal  Tea tree (arbre à Thé)  et Ravintsara.
Formulé avec les huiles essentielles purifiantes de Tea tree (arbre à Thé)  et Ravintsara
 Formule non desséchante  pour des mains douces et hydratées. Beurre de karité Le beurre de karité pur est un émollient naturel qui, guérit et protège la peau. Il protège la peau des méfaits du soleil, l''adoucit et régénère les peaux abîmées. Il nourrit également les cheveux et leur redonne brillance et beauté. Il est traditionnellement utilisé pour nourrir la peau, pour le garder souple et jeune. Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes. Le Beurre de Karité rétablit l''élasticité naturelle de la peau. Riche en vitamines A, D, E, F mais aussi en latex et en insaponifiables (qui empêche la transformation en savon),
l''huile de noix de coco Cette huile possède des vertus émollientes et adoucissantes exceptionnelles. Elle est un antioxydant naturel, qui aide à lutter contre les radicaux libres, ralentir le processus de vieillissement de la peau et rajeunir les cellules. l''huile d''olive l''huile d''olive est un excellent hydratant et convient à tous types de peau. Elle aide à préserver l''hydratation naturelle de la peau et la laisse hydratée et éclatante. Le pouvoir hydratant de l''huile d''olive en fait un excellent soin pour les peaux très sèches. Riche en vitamine E. l''huile de tournesol Elle adoucit la peau, prévient son vieillissement, renforce le système immunitaire, rend les cheveux doux, souples et brillants, limite leur perte et leur casse et favorise leur croissance. Parfum fruit de la passion.
Géranium est très efficace Pour assécher une peau trop grasse, hydrater une peau sèche et refermer les pores dilatés de la peau. La rose est connue pour ses actions régénérant cutanées puissantes et anti-âges. Elle est idéale pour nourrir les peaux sèches, abîmées et couperosées, lutter contre les rides et atténuer les vergetures et cicatrices. Ingrédients issus de l''agriculture biologique.', 'Ingrédients :  INCI:  potassium  sunflower seed oil (huile de tournesol)),  Aqua ( eau), Potassium cocate (huile de noix de coco saponifié),  Potassium  oliveate (huile d''olive saponifié) , Butyrospermum parkii butter( beurre de karité saponifié), tocopheryl acetate( vitamine E naturelle), Melaleuca alternifolia leaf oil( arbre à thé) ; Cinnamomum camphora Linalooliferum leaf oil ( huile essentielle de Ravintsara)', '250ml', 250, 7.50, 5, 2),

('Vanille 150g', 'Beurre corporel  crémeux.hydratation durable et rend votre peau étonnamment lisse:les peaux abîmées, (très) sèches, normales, sensibles et matures : le corps, le visage, les mains, les pieds et le cuir chevelu, pour l''hydratation, le massage et le rasage. Fabriqué ', 'Un beurre corporel crémeux qui  fournit une hydratation durable et rend votre peau étonnamment lisse. Il est fait avec 60 % beurre de karité biologique, l''un des meilleurs émollients de la nature.
D''autres ingrédients clés comprennent : le beurre de cacao pour adoucir et enrichir votre peau ; l''huile de noix de coco pour lisser, nourrir et ajouté une lueur chaude à votre peau ; l''huile de tournesol, qui est riche en omégas pour  garder votre peau souple, élastique et saine ; la vitamine E pour  préserver la jeunesse de votre peau et prévenir le vieillissement prématuré.
Un beurre végétalien,  fait main. Parfumé à la vanille', 'Ingrédients : INCI : butyrospermum parkii (beurre de karité), butter cocos nucifera (huile de coco),  helianthus annuus (huile de tournesol),  theobroma cacao (beurre de cacao), Vanilla planifolia fruit ( vanille)   , Tocopheryl acetate ( vitamine E) . Allergene :  sans allergène.','150g', 150, 14, 6, 3),

('Vanille 50g', 'Beurre corporel  crémeux.hydratation durable et rend votre peau étonnamment lisse:les peaux abîmées, (très) sèches, normales, sensibles et matures : le corps, le visage, les mains, les pieds et le cuir chevelu, pour l''hydratation, le massage et le rasage. Fabriqué ', 'Un beurre corporel crémeux qui  fournit une hydratation durable et rend votre peau étonnamment lisse. Il est fait avec 60 % beurre de karité biologique, l''un des meilleurs émollients de la nature.
D''autres ingrédients clés comprennent : le beurre de cacao pour adoucir et enrichir votre peau ; l''huile de noix de coco pour lisser, nourrir et ajouté une lueur chaude à votre peau ; l''huile de tournesol, qui est riche en omégas pour  garder votre peau souple, élastique et saine ; la vitamine E pour  préserver la jeunesse de votre peau et prévenir le vieillissement prématuré.
Un beurre végétalien,  fait main. Parfumé à la vanille', 'Ingrédients : INCI : butyrospermum parkii (beurre de karité), butter cocos nucifera (huile de coco),  helianthus annuus (huile de tournesol),  theobroma cacao (beurre de cacao), Vanilla planifolia fruit ( vanille)   , Tocopheryl acetate ( vitamine E) . Allergene :  sans allergène.','50g', 50, 14, 6, 3),

('Géranium & Rose 150g', 'Beurre corporel  crémeux.hydratation durable et rend votre peau étonnamment lisse:les peaux abîmées, (très) sèches, normales, sensibles et matures : le corps, le visage, les mains, les pieds et le cuir chevelu, pour l''hydratation, le massage et le rasage. Fabriqué', 'Un beurre corporel crémeux qui  fournit une hydratation durable et rend votre peau étonnamment lisse. Il est fait avec 60 % beurre de karité biologique, l''un des meilleurs émollients de la nature.
D''autres ingrédients clés comprennent : le beurre de cacao pour adoucir et enrichir votre peau ; l''huile de noix de coco pour lisser, nourrir et ajouté une lueur chaude à votre peau ; l''huile de tournesol, qui est riche en omégas pour  garder votre peau souple, élastique et saine ; la vitamine E pour  préserver la jeunesse de votre peau et prévenir le vieillissement prématuré.
Un beurre végétalien, fait main. Parfumé au huiles essentielles de géranium et rose.', 'Ingrédients :  INCI : butyrospermum parkii (beurre de karité), butter cocos nucifera (huile de coco),  helianthus annuus (huile de tournesol),  theobroma cacao (beurre de cacao),  Pelargonium asperum  oil( Geranuim) , Aniba rosaeodora wood ( rose des bois) , Tocopheryl acetate( Vitamine E) , allergene :  citral, geraniol linalool, citronellol, limonene, benzyl benzoate.','150g', 150, 14, 1, 3),

('Géranium & Rose 50g', 'Beurre corporel  crémeux.hydratation durable et rend votre peau étonnamment lisse:les peaux abîmées, (très) sèches, normales, sensibles et matures : le corps, le visage, les mains, les pieds et le cuir chevelu, pour l''hydratation, le massage et le rasage. Fabriqué
', 'Un beurre corporel crémeux qui  fournit une hydratation durable et rend votre peau étonnamment lisse. Il est fait avec 60 % beurre de karité biologique, l''un des meilleurs émollients de la nature.
D''autres ingrédients clés comprennent : le beurre de cacao pour adoucir et enrichir votre peau ; l''huile de noix de coco pour lisser, nourrir et ajouté une lueur chaude à votre peau ; l''huile de tournesol, qui est riche en omégas pour  garder votre peau souple, élastique et saine ; la vitamine E pour  préserver la jeunesse de votre peau et prévenir le vieillissement prématuré.
Un beurre végétalien, fait main. Parfumé au huiles essentielles de géranium et rose.', 'Ingrédients :  INCI : butyrospermum parkii (beurre de karité), butter cocos nucifera (huile de coco),  helianthus annuus (huile de tournesol),  theobroma cacao (beurre de cacao),  Pelargonium asperum  oil( Geranuim) , Aniba rosaeodora wood ( rose des bois) , Tocopheryl acetate( Vitamine E) , allergene :  citral, geraniol linalool, citronellol, limonene, benzyl benzoate.','50g', 50, 14, 1, 3),

('Fruit de la passion 150g', 'Beurre corporel  crémeux.hydratation durable et rend votre peau étonnamment lisse:les peaux abîmées, (très) sèches, normales, sensibles et matures : le corps, le visage, les mains, les pieds et le cuir chevelu, pour l''hydratation, le massage et le rasage.Fabriqué à', 'Un beurre corporel crémeux qui  fournit une hydratation durable et rend votre peau étonnamment lisse. Il est fait avec 60 % beurre de karité biologique, l''un des meilleurs émollients de la nature.
D''autres ingrédients clés comprennent : le beurre de cacao pour adoucir et enrichir votre peau ; l''huile de noix de coco pour lisser, nourrir et ajouté une lueur chaude à votre peau ; l''huile de tournesol, qui est riche en omégas pour  garder votre peau souple, élastique et saine ; la vitamine E pour  préserver la jeunesse de votre peau et prévenir le vieillissement prématuré.
Un beurre végétalien, fait main. Parfumé à l''huile essentielle de fruit de la passion', 'Ingrédients :INCI :  butyrospermum parkii (beurre de karité), butter cocos nucifera (huile de coco),  helianthus annuus (huile de tournesol),  theobroma cacao (beurre de cacao) Passiflora edulis var( fruit de la passion) Tocopheryl acetate( vitamine E)  Allergene :  benzyl benzoate, eugenol, geranol, Hexyl cinnamic aldehyde','150g', 150, 14, 7, 3),

('Fruit de la passion 50g', 'Beurre corporel  crémeux.hydratation durable et rend votre peau étonnamment lisse:les peaux abîmées, (très) sèches, normales, sensibles et matures : le corps, le visage, les mains, les pieds et le cuir chevelu, pour l''hydratation, le massage et le rasage.Fabriqué à', 'Un beurre corporel crémeux qui  fournit une hydratation durable et rend votre peau étonnamment lisse. Il est fait avec 60 % beurre de karité biologique, l''un des meilleurs émollients de la nature.
D''autres ingrédients clés comprennent : le beurre de cacao pour adoucir et enrichir votre peau ; l''huile de noix de coco pour lisser, nourrir et ajouté une lueur chaude à votre peau ; l''huile de tournesol, qui est riche en omégas pour  garder votre peau souple, élastique et saine ; la vitamine E pour  préserver la jeunesse de votre peau et prévenir le vieillissement prématuré.
Un beurre végétalien, fait main. Parfumé à l''huile essentielle de fruit de la passion', 'Ingrédients :INCI :  butyrospermum parkii (beurre de karité), butter cocos nucifera (huile de coco),  helianthus annuus (huile de tournesol),  theobroma cacao (beurre de cacao) Passiflora edulis var( fruit de la passion) Tocopheryl acetate( vitamine E)  Allergene :  benzyl benzoate, eugenol, geranol, Hexyl cinnamic aldehyde','50g', 50, 14, 7, 3),

('Mangue & citron vert 150g', 'Beurre corporel  crémeux.hydratation durable et rend votre peau étonnamment lisse:les peaux abîmées, (très) sèches, normales, sensibles et matures : le corps, le visage, les mains, les pieds et le cuir chevelu, pour l''hydratation, le massage et le rasage. Fabriqué', 'Un beurre corporel crémeux qui  fournit une hydratation durable et rend votre peau étonnamment lisse. Il est fait avec 60 % beurre de karité biologique, l''un des meilleurs émollients de la nature.
D''autres ingrédients clés comprennent : le beurre de cacao pour adoucir et enrichir votre peau ; l''huile de noix de coco pour lisser, nourrir et ajouté une lueur chaude à votre peau ; l''huile de tournesol, qui est riche en omégas pour  garder votre peau souple, élastique et saine ; la vitamine E pour  préserver la jeunesse de votre peau et prévenir le vieillissement prématuré.
Un beurre végétalien, non testé sur les animaux, fait main.', 'Ingrédients INCI : butyrospermum parkii (beurre de karité), butter cocos nucifera (huile de coco),  helianthus annuus (huile de tournesol),  theobroma cacao (beurre de cacao),  ,  Citrus limon peel oil( citron) Mangifera Indica( mangue), Tocopheryl acetate ( vitamine E)  Allergene: citral, geraniol, linalool,limonene,benzyl benzoate, benzyl salicylate,citronellol, hexyl cinnanic, liliestralis22, metyl ionone, orange terpenes/d-limonene.','150g', 150, 14, 6, 3),

('Mangue & citron vert 50g', 'Beurre corporel  crémeux.hydratation durable et rend votre peau étonnamment lisse:les peaux abîmées, (très) sèches, normales, sensibles et matures : le corps, le visage, les mains, les pieds et le cuir chevelu, pour l''hydratation, le massage et le rasage. Fabriqué', 'Un beurre corporel crémeux qui  fournit une hydratation durable et rend votre peau étonnamment lisse. Il est fait avec 60 % beurre de karité biologique, l''un des meilleurs émollients de la nature.
D''autres ingrédients clés comprennent : le beurre de cacao pour adoucir et enrichir votre peau ; l''huile de noix de coco pour lisser, nourrir et ajouté une lueur chaude à votre peau ; l''huile de tournesol, qui est riche en omégas pour  garder votre peau souple, élastique et saine ; la vitamine E pour  préserver la jeunesse de votre peau et prévenir le vieillissement prématuré.
Un beurre végétalien, non testé sur les animaux, fait main.', 'Ingrédients INCI : butyrospermum parkii (beurre de karité), butter cocos nucifera (huile de coco),  helianthus annuus (huile de tournesol),  theobroma cacao (beurre de cacao),  ,  Citrus limon peel oil( citron) Mangifera Indica( mangue), Tocopheryl acetate ( vitamine E)  Allergene: citral, geraniol, linalool,limonene,benzyl benzoate, benzyl salicylate,citronellol, hexyl cinnanic, liliestralis22, metyl ionone, orange terpenes/d-limonene.','50g', 50, 14, 6, 3),

('Muguet & Néroli 150g', 'Beurre corporel  crémeux.hydratation durable et rend votre peau étonnamment lisse:les peaux abîmées, (très) sèches, normales, sensibles et matures : le corps, le visage, les mains, les pieds et le cuir chevelu, pour l''hydratation, le massage et le rasage. Fabriqué', 'Un beurre corporel crémeux qui  fournit une hydratation durable et rend votre peau étonnamment lisse. Il est fait avec 60 % beurre de karité biologique, l''un des meilleurs émollients de la nature.
D''autres ingrédients clés comprennent : le beurre de cacao pour adoucir et enrichir votre peau ; l''huile de noix de coco pour lisser, nourrir et ajouté une lueur chaude à votre peau ; l''huile de tournesol, qui est riche en omégas pour  garder votre peau souple, élastique et saine ; la vitamine E pour  préserver la jeunesse de votre peau et prévenir le vieillissement prématuré.
Un beurre végétalien, fait main.Parfumé aux huiles essentielles de muguet et néroli', 'Ingrédients : INCI :  butyrospermum parkii (beurre de karité), butter cocos nucifera (huile de coco),  helianthus annuus (huile de tournesol),  theobroma cacao (beurre de cacao) , Citrus aurantium amara flower oil( Neroli)  /  convallaria majalis( Muguet)  , Tocopheryl acetate ( vitamine E) . Allergene : citral, hydroxylcitronellal, geraniol,linalool, citronellol,limonene.','150g', 150, 14, 6, 3),

('Muguet & Néroli 50g', 'Beurre corporel  crémeux.hydratation durable et rend votre peau étonnamment lisse:les peaux abîmées, (très) sèches, normales, sensibles et matures : le corps, le visage, les mains, les pieds et le cuir chevelu, pour l''hydratation, le massage et le rasage. Fabriqué', 'Un beurre corporel crémeux qui  fournit une hydratation durable et rend votre peau étonnamment lisse. Il est fait avec 60 % beurre de karité biologique, l''un des meilleurs émollients de la nature.
D''autres ingrédients clés comprennent : le beurre de cacao pour adoucir et enrichir votre peau ; l''huile de noix de coco pour lisser, nourrir et ajouté une lueur chaude à votre peau ; l''huile de tournesol, qui est riche en omégas pour  garder votre peau souple, élastique et saine ; la vitamine E pour  préserver la jeunesse de votre peau et prévenir le vieillissement prématuré.
Un beurre végétalien, fait main.Parfumé aux huiles essentielles de muguet et néroli', 'Ingrédients : INCI :  butyrospermum parkii (beurre de karité), butter cocos nucifera (huile de coco),  helianthus annuus (huile de tournesol),  theobroma cacao (beurre de cacao) , Citrus aurantium amara flower oil( Neroli)  /  convallaria majalis( Muguet)  , Tocopheryl acetate ( vitamine E) . Allergene : citral, hydroxylcitronellal, geraniol,linalool, citronellol,limonene.','50g', 50, 14, 6, 3),

('karité &Chocolat 3.5g', 'Au délicieux chocolat,   protège vos lèvres tout en les  hydratant  toute la journée. Incroyable douceur à vos lèvres. Pour tous types de peau. Fabriqué à la main à partir d''ingrédients naturels et biologiques”
', 'Au délicieux chocolat,   protège vos lèvres tout en les  hydratant  toute la journée. Incroyable douceur à vos lèvres. Pour tous types de peau. Fabriqué à la main à partir d''ingrédients naturels et biologiques”
', 'Ingredients: Butyrospermum parkii butter (beurre de karité),sunflower seed oil, theobrom cacao, cire d''abeille, gout chocolat, Tocopheryl acetate.','3.5g', 4, 3.50, 20, 4),

('Citron & mangue 3.5g
', 'Au délicieuse mangue et citron vert, Ce baume à lèvres  protège vos lèvres tout en les hydratant  toute la journée. Incroyable douceur à vos lèvres. Pour tous types de peau. Fabriqué à la main à partir d''ingrédients naturels et ', 'Au délicieuse mangue et citron vert, Ce baume à lèvres  protège vos lèvres tout en les hydratant  toute la journée. Incroyable douceur à vos lèvres. Pour tous types de peau. Fabriqué à la main à partir d''ingrédients naturels et ', 'Ingredients: Butyrospermum parkii butter (beurre de karité),sunflower seed oil, theobrom cacao, cire d''abeille, gout mangue et citron, Tocopheryl acetate.','3.5g', 4, 3.50, 25, 4),

('Beurre de karité pur non raffiné/150g', 'Émollient naturel( 100% biologique)  qui protège la peau. utilisé pour : la sécheresse extrême, Les vergetures( empêche totalement la formation des vergetures sur le ventre pendant la grosse) et la prévention des rides.  Riche en vitamines A, D, E,', 'Ce beurre de karité pur non raffiné 100% est naturel et végétalien. Idéal pour les peaux se nsibles, une crème hydratante de qualité supérieure qui restaure l''élasticité naturelle de la peau. Émolliente, il est utilisé  pour un large éventail de problèmes de peau. Protecteur de la peau quotidien pour une peau d''apparence jeune et plus saine.
Le beurre de karité provient de l''arbre de Karité, qui ne pousse que dans les régions de savane en l''afrique. Les propriétés émollientes de beurre de karité ont été prouvées depuis des siècles en Afrique. Il est traditionnellement utilisé pour nourrir la peau et  l''a gardée souple et jeune.
Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes.
Le Beurre de Karité contient une abondance d''ingrédients de guérison, y compris les vitamines, minéraux, protéines, et un profil unique d''acide gras. Il est un hydratant actif supérieur. Beurre de Karité rétablit effectivement l''élasticité naturelle de la peau.
Le beurre de karité permet à votre peau d''absorber l''humidité de l''air, et par conséquent, elle  devient plus douce et reste hydratée plus longtemps.
Les utilisateurs réguliers de pur beurre de karité non raffiné ont  une  peau plus douce plus saine.', 'Liste des ingrédients','150g', 150, 12, 3, 5),

('Beurre de karité pur non raffiné 50g', 'Émollient naturel( 100% biologique)  qui protège la peau. utilisé pour : la sécheresse extrême, Les vergetures( empêche totalement la formation des vergetures sur le ventre pendant la grosse) et la prévention des rides.  Riche en vitamines A, D, E,', 'Ce beurre de karité pur non raffiné 100% est naturel et végétalien. Idéal pour les peaux sensibles, une crème hydratante de qualité supérieure qui restaure l''élasticité naturelle de la peau. Émolliente, il est utilisé  pour un large éventail de problèmes de peau. Protecteur de la peau quotidien pour une peau d''apparence jeune et plus saine.
Le beurre de karité provient de l''arbre de Karité, qui ne pousse que dans les régions de savane en l''Afrique. Les propriétés émollientes de beurre de karité ont été prouvées depuis des siècles en Afrique. Il est traditionnellement utilisé pour nourrir la peau et  l''a gardée souple et jeune.
Il est également utilisé pour traiter une variété d''affections cutanées telles que: l''eczéma, irritations, sécheresse extrême, vergetures et la prévention des rides, des brûlures, des coupures et des petites plaies de la peau, les soins après-soleil, les piqûres d''insectes.
Le Beurre de Karité contient une abondance d''ingrédients de guérison, y compris les vitamines, minéraux, protéines, et un profil unique d''acide gras. Il est un hydratant actif supérieur. Beurre de Karité rétablit effectivement l''élasticité naturelle de la peau.
Le beurre de karité permet à votre peau d''absorber l''humidité de l''air, et par conséquent, elle  devient plus douce et reste hydratée plus longtemps.
Les utilisateurs réguliers de pur beurre de karité non raffiné ont  une  peau plus douce plus saine.', 'Liste des ingrédients','50g', 50, 12, 3, 5),


('mini- Pochon noël', 'Pochon  Noel ', 'Pochon Noel  : 1 savon solide 155g , 1beurre corporel 50g, 1 stick à lèvres . ', '', 'Baluchon 570 g', 570, 19.50, 20, 6),

('Maxi-Pochon Noel', 'Pochon Noel : 1 savon liquide 500ml , 1 beurre corporel 150g, 1 stick à lèvres ', 'Pochon Noel : 1 savon liquide 500ml , 1 beurre corporel 150g, 1 stick à lèvres . ', 'ingrédients','Baluchon 690g', 690, 31.50, 24, 6),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 5 euros', '','', 1, 5, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 10 euros', '','', 1, 10, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 15 euros', '','', 1, 15, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 20 euros', '','', 1, 20, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 25 euros', '','', 1, 25, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 30 euros', '','', 1, 30, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 35 euros', '','', 1, 35, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 40 euros', '','', 1, 40, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 45 euros', '','', 1, 45, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 50 euros', '','', 1, 50, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 55 euros', '','', 1, 55, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 60 euros', '','', 1, 60, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 65 euros', '','', 1, 65, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 70 euros', '','', 1, 70, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 75 euros', '','', 1, 75, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 80 euros', '','', 1, 80, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 85 euros', '','', 1, 85, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 90 euros', '','', 1, 90, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 95 euros', '','', 1, 95, 99, 7),

('Carte Cadeau', 'Carte Cadeau', 'Carte Cadeau de 100 euros', '','', 1, 100, 99, 7);


COMMIT;
